// Nomi ricavati dalla stagione 2024-25, i piu' usati per primi.
const ESERCIZI = [
"W.U",
"Batt/rice",
"Coppie",
"BAGHERONE",
"MINI SET P/A",
"MURO DAI PLINTI",
"Rice",
"MINI SET F/B",
"Rice / Attacco",
"Difesa e alzata",
"RICE campo A, DIFESA campo B",
"ALZATE",
"MINI SET PALLA",
"DOPPIA DIFESA e ALZATA",
"Mini Set PALLA SPOSTATA",
"DIFESA",
"TERZETTI",
"QUARTETTI",
"Rice QUADRANTI",
"DOPPIO ATTACCO",
"MINI SET PALLA !",
"MINI SET DA PALLA SPOSTATA",
"ALZATA",
"BATTUTA",
"Muro a 3",
"CIRCUITO",
"GIOCO ALZATE",
"C/P + conferma P/A",
"BATT/RICE e ATTACCO",
"MINI SET F/B BASE 7",
"ATTACCO DI PALLA ALTA",
"GIOCO FEMMINILE DA F/B",
"Palleggiatori vs Centrali",
"rice/attacco CENTRO/AVANTI",
"Batt/Rice con attacco opposto",
"Hunger Games - C/P con conferma",
"MINI SET da ATTACCO PIEDI A TERRA",
"C/P + PALLA ! + F/B DA TERZO TOCCO",
"Doppia difesa con alzata e copertura",
"Muro",
"7/pipe",
"Pipe/8",
"Pipe/5",
"attacco",
"PRE GARA",
"Stazioni",
"RICEZIONE",
"BATT RICE",
"W.U. libero",
"Centro/Pipe",
"Gioco Alzata",
"Rice da cubo",
"Muro - AIUTI",
"MURO POSTI 4",
"ATTACCO 1T/8",
"Difesa pag.2",
"Royal Rumble",
"Hunger Games",
"7/palla sopra",
"Alzate liberi",
"LAVORO GRUPPI",
"DIFESA PLINTI",
"liberi alzate",
"W.U. pre-gara",
"PALLA SPOSTATA",
"COPPIE GUIDATA",
"Battute libere",
"Battuta / Rice",
"ATTACCO vs Muro",
"MINI SET 1 VS 1",
"MINI SET da f/b",
"ATTACCO 7/SOPRA",
"Assetti di rice",
"Mini-Set Base 7",
"SERIE DI PALLONI",
"Torneo bagherone",
"MURO PER CENTRALI",
"MURO - AIUTI PIPE",
"DIFESA DAI PLINTI",
"F/B + CONFERMA P/A",
"ATTACCO 2/3 DIETRO",
"Attacco 2/3 AVANTI",
"3vs3 seconda linea",
"Cesto Palleggiatori",
"MURO - PROPEDEUTICO",
"F/B con vincolo 2/3",
"ATTACCO PRIMO TEMPO",
"BATT/RICE QUADRANTI",
"C/P + P/A + P/A x B",
"1vs1 singoli da F/B",
"terzetti con navetta",
"PALLA COPPIE GUIDATA",
"ATTACCO su due terzi",
"SINTETICO 2/3 AVANTI",
"P# vs P! contro Muro",
"palleggiatori con me",
"Circuiti rice/difesa",
"LAVORO FISICO TECNICO",
"BATT/Rice no palleggi",
"SINTETICO ATTACCO 2/3",
"SINTETICO META' CAMPO",
"C/P + F/B + P/A per B",
"Palleggiatori palla !",
"Batt / Rice solo flot",
"Difesa fuori dal campo",
"Aiuti a Muro su PIPE 1",
"DOPPIO DIFESA e ALZATA",
"C/P + Conferma Palla !",
"DOPPIO ATTACCO vs MURO",
"RICE CON SPARA PALLONI",
"Rice Coppie lungolinea",
"Rice / Attacco vs Muro",
"Sovraccarico al centro",
"palla a coppie guidata",
"Battuta/Rice con alzata",
"Attacco esterni vs muro",
"MANO DAI PLINTI SINGOLO",
"MINI SET F/B IN LETTURA",
"Rice singola come pag.2",
"Batt/Rice/Attacco pag.2",
"rice/attacco vs fitball",
"Battuta rice linea/diago",
"Terzetti difesa e alzata",
"RICEZIONE + F/B a BASE 7",
"MINI SET P/A RICE BRUTTA",
"MINI SET F/B per 7/Sopra",
"MINI SET F/B vincolo 2/3",
"MINI SET GIOCO FEMMINILE",
"MINI SET CON VINCOLI 2/3",
"Batt / Rice su due campi",
"Rice / Attacco al centro",
"SINTETICO ATTACCO Base 7",
"Rice e attacco alternati",
"Difesa / Alzata terzetti",
"Doppia Difesa con attacco",
"Muro centrali con esterni",
"Batt/Rice con primo tempo",
"BATTUTA RICE come a pag.2",
"F/B con PUNTO DOPO DIFESA",
"DOPPIA DIFESA E COPERTURA",
"MINI SET P/A NO PALLEGGIO",
"MINI SET P/A PER MURO A 3",
"MINI SET DA DIFESA LIBERA",
"Mini set Palla !- vs Muro",
"C/P + conferma da attacco",
"Doppio attacco primo tempo",
"RICE con ATTACCO al CENTRO",
"SINTETICO ATTACCO 1-7-PIPE",
"Doppio attacco contro muro",
"3 palloni, 2 volte x campo",
"Batt / Rice con due plinti",
"Combinazioni 1/palla rapida",
"Difesa da plinto lungolinea",
"gruppo ridotto - ALZATA P/A",
"C/P + F/B CENTRO/PIPE + P/A",
"MINI SET DA PALLA DIFFICILE",
"MINI SET DA F/B TERZO TOCCO",
"BATT/RICE/ATTACCO AL CENTRO",
"Batt / Rice per Centro/Pipe",
"Mini-Set partenza da Difesa",
"C/P + F/B per B + P/A per A",
"Difesa / Alzata a quartetto",
"Mini set 10 palloni di fila",
"SINTETICO 7/SOPRA O 1/DIETRO",
"C/P + P/A + battuta no bonus",
"Primo Tempo in ricostruzione",
"Rice e attacco di primo tempo",
"Palleggiatori contro centrali",
"MURO - POSIZIONAMENTO E TEMPO",
"COPPIE (PALLEGGIATORI CON ME)",
"C/P + CONFERMA PALLA SPOSTATA",
"MINI SET CON PARTENZA DA MURO",
"COPERTURE VS MURO ARTIFICIALE",
"Battuta e rice con primo tempo",
"ATTACCO 2/3 AVANTI vs Sestetto",
"MINI SET P/A CON MURO CHIAMATO",
"Muro vs palleggio agli esterni",
"C/P vincolante + P/A a + P/A b",
"Mini-Set partenza muro no muro",
"Mini Set base 7 con vincoli 2/3",
"BATTUTA + F/B per B + P/A per B",
"Riscaldamento di battuta e rice",
"F/B PUNTO con PUNTO DOPO DIFESA",
"C/P + F/B CENTRO/PIPE + PALLA !",
"C/P + P/A + SPOSTATA - 2x CAMPO",
"MINI SET CON VINCOLI DI OPZIONE",
"Battuta campo A, difesa campo B",
"C/P + conferma di palla spostata",
"Mini-Set da F/B con sovraccarico",
"BATT/RICE CAMPO A, DIFESA CAMPO B",
"C/P + P/A per A + F/B per B + C/P",
"C/P + F/B con vincoli + P/A per A",
"Mini-Set da palla brutta 3° tocco",
"Difesa CON APPOGGIO e arretramento",
"C/P VINCOLANTE + F/B per B + PA x B",
"Mini Set con F/B e attacco da fuori",
"2xCAMPO: C/P VINCOLANTE + F/B + P/A",
"Muro dai plinti singolo, poi doppio",
"Bagherone 4vs4 con attacco di testa",
"Hunger Games - C/P con conferma P/A",
"F/B per Muro 1vs1 + F/B per lettura",
"C/P + P/A x A + F/B x B + Battuta A",
"BATT/RICE con SECONDA PALLA SPOSTATA",
"bagherone a due tocchi piedi a terra",
"MINI SET SCELTA palla muro / no muro",
"Battuta - profondità vs farla cadere",
"Mini-Set palla !- da giocare vs muro",
"C/P + palla !- per B + palla #+ per B",
"Attacco di palla alta vs muro fitball",
"Attacco vs Muro (Differenziare # / -)",
"C/P + F/B x B + palla ! x B + P/A x B",
"C/P VINCOLANTE + F/B per B + P/A per A",
"C/P VINCOLANTE + F/B per B + P/A per B",
"MINI SET DA F/B CON OPZIONE VS LETTURA",
"C/P + conferma F/B per Centro/Pipe (A)",
"C/P + F/B per B + P/A per A + BATTUTA A",
"C/P + CONFERMA PALLA DIVERSA DALLA RICE",
"MURO - posizionamento su palla e timing",
"C/P per A + difesa e alzata di P/A per B",
"Liberi: difesa con focus su arretramento",
"2xCAMPO: C/P + P/A per B + palla ! per A",
"Alzate prima in bagher, poi in palleggio",
"C/P + F/B Centro/Pipe + P/A per muro a 3",
"CP (errore -1) + CONFERMA P/A (errore -1)",
"MURO DAI PLINTI prima singolo, poi doppio",
"C/P (errore -2) + conferma P/A (errore -1)",
"ATTACCO DI PALLA ALTA CON PARTENZA DA MURO",
"MINI SET CON SERIE DI P/A PER CHI FA PUNTO",
"C/P + CONFERMA con PALLA DIVERSA DALLA RICE",
"F/B 2/3 + CONFERMA P/A con MURO 3 OBBLIGATO",
"MURO assistenze e doppio passo per centrali",
"C/P + PALLA ! + PALLA DA DIFESA DEL CENTRALE",
"C/P + PALLE CONSECUTIVE (F/B, !, P/A, P/A...)",
"C/P + F/B c/p/p + P/A + P/A per B + Battuta A",
"C/P + seconda palla vincolata stesso attaccante",
"C/P VINCOLANTE + P/A per B + P/A per A + BATTUTA",
"C/P vincolante + F/B per B + P/A per B + BATTUTA",
"DIFESA CON APPOGGIO - tocco palla e arretramento",
"C/P + F/B per B 2/3 AVANTI + PALLA SPOSTATA per A",
"C/P VINCOLATO + BATT. A + PALLA DIVERSA DALLA RICE",
"C/P VINCOLANTE + PALLA DA ATTACCO + F/B TERZO TOCCO",
"C/P vincolante + F/B 1/avanti o 7/sopra + P/A per A",
"C/P + P/A per A + P/A per B + F/B per B + C/P base 7",
"DIFESA: spara palloni in un campo, doppia sull'altro",
"Primo tempo e 8 - centrali appoggiano in arretramento",
"Rice S e L da due plinti, difesa C, P, O. campo unico",
"3 palloni: C/P vincolante + F/B centro/pipe + F/B x B",
"C/P vincolante + conferma stesso attaccante + Battuta A",
"C/P + P/A per A + F/B centro/pipe per A + palla ! per B",
"Primi tempi: prima normali poo da appoggio-passo-stacco",
"LAVORO PALLEGGIATORI di lettura spostamento e pre-salto",
"C/P CON DOPPIO PALLONE RILANCIATO APPENA FINISCE IL PUNTO",
"Muri dai plinti diago/mano/linea con chiusura del centrale",
"Battuta con sviluppo esterni / pipe, difesa con palla alta",
"C/P + CONFERMA (B: F/B no primo tempo, A: attacco da fuori)",
"C/P + conferma di palla obbligata a chi ha attaccato la prima",
"Bagherone con attacco di testa poi attacco di palla alta brutta",
"C/P Vincolante + P/A per Muro a 3 + F/B da terzo tocco a base 7",
"C/P + CONFERMA palla +! per A / C/P + conferma P/A per muro a 3",
"C/P conferma + a) P/A !- b) F/B vincolata (2/3 avanti su att a 3)",
"C/P + serie di palloni avversari per fare punto dalla seconda palla",
"2xCampo: Battuta + conferma F/B per A vs Battuta + conferma di P/A x B",
"DOPPIO PALLONE: C/P + se prima palla a terra, F/B per gli altri attaccanti, altrimenti stesso attaccante"
];
